export type Category = "Figure" | "Mangá" | "Miniatura" | "Acessório";
export type Side = "hero" | "villain";

export type Product = {
  id: string;
  name: string;
  character: string;
  anime: string;
  kanji: string;
  category: Category;
  side?: Side; // herói (padrão) ou vilão
  tagline: string;
  price: string;
  oldPrice?: string;
  rarity: "Comum" | "Raro" | "Lendário" | "Mítico";
  hue: string;
  image?: string; // /characters/*.png — quando ausente, card usa arte da marca
};

// 🔥 Figures dos personagens marcantes (imagens reais)
export const products: Product[] = [
  {
    id: "naruto",
    name: "Naruto Uzumaki",
    character: "Naruto Uzumaki",
    anime: "Naruto Shippuden",
    kanji: "渦",
    category: "Figure",
    tagline: "O ninja que nunca desiste.",
    price: "R$ 189,90",
    oldPrice: "R$ 249,90",
    rarity: "Lendário",
    hue: "#ff8a1e",
    image: "/characters/naruto.png",
  },
  {
    id: "luffy",
    name: "Monkey D. Luffy",
    character: "Monkey D. Luffy",
    anime: "One Piece",
    kanji: "海",
    category: "Figure",
    tagline: "O futuro Rei dos Piratas.",
    price: "R$ 199,90",
    rarity: "Lendário",
    hue: "#e23b2e",
    image: "/characters/luffy.png",
  },
  {
    id: "goku",
    name: "Goku — Instinto Superior",
    character: "Son Goku",
    anime: "Dragon Ball Super",
    kanji: "悟",
    category: "Figure",
    tagline: "Poder que ultrapassa os deuses.",
    price: "R$ 229,90",
    oldPrice: "R$ 299,90",
    rarity: "Mítico",
    hue: "#c0c6ff",
    image: "/characters/goku.png",
  },
  {
    id: "gojo",
    name: "Satoru Gojo",
    character: "Satoru Gojo",
    anime: "Jujutsu Kaisen",
    kanji: "呪",
    category: "Figure",
    tagline: "O feiticeiro mais forte. Nada além do azul.",
    price: "R$ 219,90",
    rarity: "Mítico",
    hue: "#3df0ff",
    image: "/characters/gojo.png",
  },
  {
    id: "eren",
    name: "Eren Yeager",
    character: "Eren Yeager",
    anime: "Attack on Titan",
    kanji: "進",
    category: "Figure",
    tagline: "Pela liberdade, ele segue em frente.",
    price: "R$ 209,90",
    rarity: "Lendário",
    hue: "#7a8b5a",
    image: "/characters/eren.png",
  },
  {
    id: "light",
    name: "Light Yagami",
    character: "Light Yagami",
    anime: "Death Note",
    kanji: "夜",
    category: "Figure",
    tagline: "Eu serei o deus do novo mundo.",
    price: "R$ 184,90",
    rarity: "Raro",
    hue: "#b8453f",
    image: "/characters/light.png",
  },
  {
    id: "gon",
    name: "Gon Freecss",
    character: "Gon Freecss",
    anime: "Hunter x Hunter",
    kanji: "狩",
    category: "Figure",
    tagline: "A determinação de um jovem caçador.",
    price: "R$ 179,90",
    rarity: "Raro",
    hue: "#27c46b",
    image: "/characters/gon.png",
  },
  {
    id: "jinwoo",
    name: "Sung Jinwoo",
    character: "Sung Jinwoo",
    anime: "Solo Leveling",
    kanji: "影",
    category: "Figure",
    tagline: "Surja. — O Monarca das Sombras.",
    price: "R$ 239,90",
    rarity: "Mítico",
    hue: "#7c5cff",
    // sem imagem ainda — card usa arte da marca (troque por foto real)
  },
  {
    id: "sasuke",
    name: "Sasuke Uchiha",
    character: "Sasuke Uchiha",
    anime: "Naruto Shippuden",
    kanji: "雷",
    category: "Figure",
    tagline: "O vingador do clã Uchiha.",
    price: "R$ 189,90",
    rarity: "Lendário",
    hue: "#7c4dff",
    image: "/characters/sasuke.png",
  },
  {
    id: "itachi",
    name: "Itachi Uchiha",
    character: "Itachi Uchiha",
    anime: "Naruto Shippuden",
    kanji: "烏",
    category: "Figure",
    tagline: "O gênio que carregou um clã nas costas.",
    price: "R$ 214,90",
    rarity: "Mítico",
    hue: "#c81a1a",
    image: "/characters/itachi.png",
  },
  {
    id: "zoro",
    name: "Roronoa Zoro",
    character: "Roronoa Zoro",
    anime: "One Piece",
    kanji: "剣",
    category: "Figure",
    tagline: "O caçador de piratas das três espadas.",
    price: "R$ 199,90",
    rarity: "Lendário",
    hue: "#2ec27e",
    image: "/characters/zoro.png",
  },
  {
    id: "vegeta",
    name: "Vegeta — Super Saiyajin",
    character: "Vegeta",
    anime: "Dragon Ball Super",
    kanji: "戦",
    category: "Figure",
    tagline: "O orgulho do príncipe dos Saiyajins.",
    price: "R$ 229,90",
    rarity: "Mítico",
    hue: "#ffd23b",
    image: "/characters/vegeta.png",
  },
  {
    id: "tanjiro",
    name: "Tanjiro Kamado",
    character: "Tanjiro Kamado",
    anime: "Demon Slayer",
    kanji: "炭",
    category: "Figure",
    tagline: "Respiração da água, coração de aço.",
    price: "R$ 189,90",
    rarity: "Raro",
    hue: "#2bb3c4",
    image: "/characters/tanjiro.png",
  },
  {
    id: "nezuko",
    name: "Nezuko Kamado",
    character: "Nezuko Kamado",
    anime: "Demon Slayer",
    kanji: "鬼",
    category: "Figure",
    tagline: "A demônia que protege os humanos.",
    price: "R$ 189,90",
    rarity: "Raro",
    hue: "#ff5a8a",
    image: "/characters/nezuko.png",
  },
  {
    id: "levi",
    name: "Levi Ackerman",
    character: "Levi Ackerman",
    anime: "Attack on Titan",
    kanji: "兵",
    category: "Figure",
    tagline: "O soldado mais forte da humanidade.",
    price: "R$ 209,90",
    rarity: "Lendário",
    hue: "#9aa3b2",
    image: "/characters/levi.png",
  },
  {
    id: "saitama",
    name: "Saitama",
    character: "Saitama",
    anime: "One Punch Man",
    kanji: "拳",
    category: "Figure",
    tagline: "Um soco. É tudo que ele precisa.",
    price: "R$ 179,90",
    rarity: "Lendário",
    hue: "#f5c518",
    image: "/characters/saitama.png",
  },
  {
    id: "killua",
    name: "Killua Zoldyck",
    character: "Killua Zoldyck",
    anime: "Hunter x Hunter",
    kanji: "雷",
    category: "Figure",
    tagline: "O assassino com coração de amigo.",
    price: "R$ 179,90",
    rarity: "Raro",
    hue: "#7fdfff",
    image: "/characters/killua.png",
  },

  // ======= VILÕES =======
  {
    id: "madara",
    name: "Madara Uchiha",
    character: "Madara Uchiha",
    anime: "Naruto Shippuden",
    kanji: "戦",
    category: "Figure",
    side: "villain",
    tagline: "O fantasma Uchiha que desafiou o mundo.",
    price: "R$ 234,90",
    oldPrice: "R$ 309,90",
    rarity: "Mítico",
    hue: "#b23bff",
    image: "/characters/madara.png",
  },
  {
    id: "pain",
    name: "Pain (Nagato)",
    character: "Nagato",
    anime: "Naruto Shippuden",
    kanji: "痛",
    category: "Figure",
    side: "villain",
    tagline: "Conheça a dor. O líder da Akatsuki.",
    price: "R$ 214,90",
    rarity: "Lendário",
    hue: "#c81a1a",
    image: "/characters/pain.png",
  },
  {
    id: "orochimaru",
    name: "Orochimaru",
    character: "Orochimaru",
    anime: "Naruto",
    kanji: "蛇",
    category: "Figure",
    side: "villain",
    tagline: "A busca proibida pela imortalidade.",
    price: "R$ 199,90",
    rarity: "Raro",
    hue: "#7d4fa0",
    image: "/characters/orochimaru.png",
  },
  {
    id: "frieza",
    name: "Freeza Dourado",
    character: "Freeza",
    anime: "Dragon Ball Super",
    kanji: "凍",
    category: "Figure",
    side: "villain",
    tagline: "O imperador do mal em sua forma dourada.",
    price: "R$ 224,90",
    rarity: "Mítico",
    hue: "#ffcf3b",
    image: "/characters/frieza.png",
  },
  {
    id: "aizen",
    name: "Sosuke Aizen",
    character: "Sosuke Aizen",
    anime: "Bleach",
    kanji: "謀",
    category: "Figure",
    side: "villain",
    tagline: "Tudo saiu como planejado.",
    price: "R$ 219,90",
    rarity: "Mítico",
    hue: "#9b6cff",
    image: "/characters/aizen.png",
  },
  {
    id: "muzan",
    name: "Muzan Kibutsuji",
    character: "Muzan Kibutsuji",
    anime: "Demon Slayer",
    kanji: "鬼",
    category: "Figure",
    side: "villain",
    tagline: "O primeiro e mais terrível dos demônios.",
    price: "R$ 209,90",
    rarity: "Lendário",
    hue: "#d1206f",
    image: "/characters/muzan.png",
  },
  {
    id: "dio",
    name: "DIO Brando",
    character: "Dio Brando",
    anime: "JoJo's Bizarre Adventure",
    kanji: "時",
    category: "Figure",
    side: "villain",
    tagline: "ZA WARUDO! O tempo está parado.",
    price: "R$ 229,90",
    oldPrice: "R$ 289,90",
    rarity: "Mítico",
    hue: "#ffd23b",
    image: "/characters/dio.png",
  },
];

// 📚 Mangás, miniaturas e acessórios (arte da marca — troque pelas suas fotos)
export const collectibles: Product[] = [
  {
    id: "box-naruto",
    name: "Box Mangá Naruto",
    character: "Naruto",
    anime: "Coleção Shippuden",
    kanji: "巻",
    category: "Mangá",
    tagline: "Box com volumes da saga completa.",
    price: "R$ 349,90",
    rarity: "Lendário",
    hue: "#ff8a1e",
    image: "/manga/naruto.jpg",
  },
  {
    id: "manga-onepiece",
    name: "One Piece — Vol. 1 ao 10",
    character: "One Piece",
    anime: "Mangá Oficial",
    kanji: "巻",
    category: "Mangá",
    tagline: "Comece a maior aventura dos mares.",
    price: "R$ 279,90",
    rarity: "Raro",
    hue: "#e23b2e",
    image: "/manga/onepiece.jpg",
  },
  {
    id: "mini-akatsuki",
    name: "Miniaturas Akatsuki",
    character: "Set Colecionável",
    anime: "Pack com 6 peças",
    kanji: "暁",
    category: "Miniatura",
    tagline: "Esquadrão completo em miniatura.",
    price: "R$ 159,90",
    rarity: "Raro",
    hue: "#c81a1a",
  },
  {
    id: "poster-jjk",
    name: "Pôster Jujutsu Kaisen",
    character: "Arte Premium",
    anime: "Impressão 40x60",
    kanji: "呪",
    category: "Acessório",
    tagline: "Energia amaldiçoada na sua parede.",
    price: "R$ 59,90",
    rarity: "Comum",
    hue: "#3df0ff",
  },
  {
    id: "box-demonslayer",
    name: "Box Mangá Demon Slayer",
    character: "Kimetsu no Yaiba",
    anime: "Coleção Completa",
    kanji: "刃",
    category: "Mangá",
    tagline: "A saga dos caçadores de demônios.",
    price: "R$ 389,90",
    rarity: "Lendário",
    hue: "#2bb3c4",
    image: "/manga/demonslayer.jpg",
  },
  {
    id: "manga-dbz",
    name: "Dragon Ball — Edição Definitiva",
    character: "Akira Toriyama",
    anime: "Mangá Oficial",
    kanji: "龍",
    category: "Mangá",
    tagline: "O clássico que definiu uma geração.",
    price: "R$ 259,90",
    rarity: "Raro",
    hue: "#ff8a1e",
    image: "/manga/dragonball.jpg",
  },
  {
    id: "chaveiros-strawhat",
    name: "Chaveiros Chapéu de Palha",
    character: "Set com 9 peças",
    anime: "One Piece",
    kanji: "鍵",
    category: "Acessório",
    tagline: "Toda a tripulação no seu bolso.",
    price: "R$ 79,90",
    rarity: "Comum",
    hue: "#e23b2e",
  },
  {
    id: "mini-bijuu",
    name: "Miniaturas Bijuu",
    character: "Set com 9 caudas",
    anime: "Naruto",
    kanji: "尾",
    category: "Miniatura",
    tagline: "As nove bestas com cauda.",
    price: "R$ 199,90",
    rarity: "Raro",
    hue: "#ff8a1e",
  },
];

export const allProducts = [...products, ...collectibles];
